### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by piao8wan** [rtarun9/Helios#6]
Severity Code Description Project File Line Suppression State Error
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/ExternalProject.cmake:2633 (message):
 error: could not find git for clone of tinygltf-populate

Severity Code Description Project File Line Suppression State Error
CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.20/Modules/FetchContent.cmake:1000 (message):
  CMake step for tinygltf failed: 1

**Comment by rtarun9** [comment]
Thank you for reporting the issue @piao8wan. Can you let me know what steps you used to build the project? Did you open the cloned repo with Visual studio, or used the cmake commands?

**Comment by piao8wan** [comment]
I open the cloned repo with Visual studio. I think everything is done automatically by the built-in tools of VS, and I did not manually configure anything.
My OS is WIN 10 Pro with Version 1803. The Windows 10 SDK version is 10.0.19041.0.

**Comment by rtarun9** [comment]
Unfortunately, I am unable to reproduce the issue. I cloned the repo, opened it in VS 2022, selected the CmakeLists.txt file (in the project root directory, not the Cmake file under the External folder), ran the Setup.bat file, and build and run the project. I am using Win 10 home build 19045.2728 with SDK version.

A few things that might be causing this:
1. Have you installed CMake tools for Visual studio?
![image](https://user-images.githubusercontent.com/75297835/230760973-58b93c8e-913a-43ae-ab67-d8b1fab6cd0d.png)

2. Perhaps check your git version? (since in the error you shared, it mentions git not found for some reason). I am currently using version 2.39.1

3. Check your cmake version (the minimum required is currently 3.20 which is high, but that might cause some issues).

4. Finally, if none of the above looks right, could you please try : ```
cmake -S . -B Build
cmake --build Build
.\Setup.bat
```
and see if the error persist? If this indeed does work, we can narrow the issue down to a Visual studio cmake error.
Again, thanks for reporting the issue.
